### ISSUE TITLE
OMP: Error #15: Initializing libomp.so

### ISSUE THREAD

**Issue by umahsn** [cytham/nanovar#12] opened 2020-07-13 18:17 UTC
I tried running Nanovar but received the following error. Can you help me figure out how to fix this?

OMP: Error #15: Initializing libomp.so, but found libiomp5.so already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
/cm/local/apps/uge/var/spool/c-0-10/job_scripts/16688858: line 1: 168456 Aborted                 (core dumped)

**Comment by cytham** [comment] 2020-07-13 22:27
Duplicate of #11 Might be an issue with matplotlib. Please try the solutions in https://stackoverflow.com/questions/53014306/error-15-initializing-libiomp5-dylib-but-found-libiomp5-dylib-already-initial and get back to me, thanks

**Comment by cytham** [comment] 2020-07-20 05:55
Hi, I will close this for now.

**Closed by cytham** 2020-07-20 05:55 UTC
Labels: duplicate
